<!--
document.writeln(" <div class=\"efusion-wrapcen\"> ");
document.writeln(" <div id=\"efusion-header\"> ");
document.writeln("      ");
document.writeln(" <div id=\"efusion-logo\"><a href=\"http://stores.ebay.com/The-Whole-Shebang-New-York\"><img src=\"http://i61.photobucket.com/albums/h76/Nimo18/new%20one1_zpsmhcqgpik.png\" width=\"155\" height=\"90\" /></a></div> ");
document.writeln("  ");
document.writeln("  ");
document.writeln(" <!--STORE SEARCH //STARTS--> ");
document.writeln(" <div id=\"efusion-search\"> ");
document.writeln("           <form action=\"/The-Whole-Shebang-New-York/_i.html\" style=\"display: inline;\" method=\"get\" name=\"Search\"> ");
document.writeln("             <div id=\"efusion-input\"> ");
document.writeln("               <input name=\"_nkw\" type=\"text\" class=\"v4sbox\" onclick=\"this.value='';\" value=\"Store Search\" size=\"13\" maxlength=\"300\" /> ");
document.writeln("             </div> ");
document.writeln("             <div id=\"efusion-submit\"> ");
document.writeln("               <input name=\"submit\" type=\"submit\"  class=\"btn-search\" /> ");
document.writeln("             </div> ");
document.writeln("           </form> ");
document.writeln(" </div> ");
document.writeln(" <!--STORE SEARCH //ENDS--> ");
document.writeln("  ");
document.writeln(" <!--STORE PAGES NAVIGATION //STARTS--> ");
document.writeln(" <div id=\"efusion-nav\"> ");
document.writeln(" 	<ul> ");
document.writeln("     	<li><a href=\"\">Contact Us</a></li> ");
document.writeln("         <li><a href=\"\">Ending Soon</a></li> ");
document.writeln("         <li><a href=\"\">New Arrivals</a></li> ");
document.writeln("         <li><a href=\"\">Add to Favorites</a></li> ");
document.writeln("         <li><a href=\"\">Home</a></li> ");
document.writeln("     </ul> ");
document.writeln(" </div> ");
document.writeln(" <!--STORE PAGES NAVIGATION //END--> ");
document.writeln("  ");
document.writeln(" <!--STORE NAVIGATION //STARTS--> ");
document.writeln(" <div id=\"efusion-menu\"> ");
document.writeln("   <div id=\"efusion-menu-holder\"> ");
document.writeln("     <ul id=\"efusionmenu\"> ");
document.writeln("     	<li><a href=\"\">MEN</a></li>  ");
document.writeln("         <li><a href=\"\">MISSY</a></li>  ");
document.writeln("         <li><a href=\"\">JUNIOR</a></li>  ");
document.writeln("         <li><a href=\"\">GIRLS</a></li> ");
document.writeln("         <li><a href=\"\">BOYS</a></li>  ");
document.writeln("         <li><a href=\"\">PLUS SIZE</a></li>  ");
document.writeln("         <li class=\"showall\"><a href=\"\">SHOW ALL</a></li> ");
document.writeln("     </ul> ");
document.writeln("   </div> ");
document.writeln(" </div> ");
document.writeln(" <!--STORE NAVIGATION //ENDS--> ");
document.writeln(" </div> ");
document.writeln("  ");
document.writeln(" <!--STORE BANNER //STARTS--> ");
document.writeln(" <div id=\"banner-holder\"> ");
document.write(' <div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 1045px; height: 300px; overflow: hidden;"> <div u="loading" style="position: absolute; top: 0px; left: 0px;"> <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block; background-color: #000; top: 0px; left: 0px;width: 1030px;height:300px;"> </div><div style="position: absolute; display: block; background: url(file:///D|/img/loading.gif) no-repeat center center; top: 0px; left: 0px;width: 1045px;height:300px;"> </div></div><div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1045px; height: 300px; overflow: hidden;"> <div> <a u="image" href="#"><img src="http://i61.photobucket.com/albums/h76/Nimo18/TheWholeShebang_zpsmuzcczlp.jpg"></a> <div u="caption" t="*" class="captionOrange" style="position:absolute; left:20px; top: 30px; width:300px; height:30px;"></div></div><div> <a u="image" href="#"><img src="http://i61.photobucket.com/albums/h76/Nimo18/TheWholeShebang_zpsmuzcczlp.jpg"></a> <div u="caption" t="*" class="captionOrange1" style="position:absolute; left:20px; top: 30px; width:300px; height:30px;"></div></div><div> <a u="image" href="#"><img src="http://i61.photobucket.com/albums/h76/Nimo18/TheWholeShebang_zpsmuzcczlp.jpg"></a> <div u="caption" t="*" class="captionOrange1" style="position:absolute; left:20px; top: 30px; width:300px; height:30px;"></div></div><div> <a u="image" href="#"><img src="http://i61.photobucket.com/albums/h76/Nimo18/TheWholeShebang_zpsmuzcczlp.jpg"></a> <div u="caption" t="*" class="captionOrange1" style="position:absolute; left:20px; top: 30px; width:300px; height:30px;"></div></div></div><span u="arrowleft" class="jssora05l" style="top: 123px; left: 8px;"> </span> <span u="arrowright" class="jssora05r" style="top: 123px; right: 8px;"> </span> </div>');
document.writeln(" 	 ");
document.writeln(" </div> ");
document.writeln(" <!--STORE BANNER //ENDS--> ");
document.writeln(" </div> ");
document.writeln("  ");

 // -->
